module Wampproto
  module Auth
    # generates ticket authentication signature
    class Ticket < Base
      @details: Hash[Symbol, untyped]

      @secret: String

      AUTH_METHOD: "ticket"

      attr_reader secret: String

      def initialize: (String secret, ?::Hash[Symbol, untyped] details) -> void

      def details: () -> Hash[Symbol, untyped]

      def authenticate: (Message::Challenge challenge) -> Message::Authenticate

      private

      def create_signature: (untyped _challenge) -> untyped
    end
  end
end

