module WampProto
  module Message
    # abort message
    class Abort
      @details: Hash[Symbol, untyped]

      @reason: String

      @args: Array[untyped]

      @kwargs: Hash[Symbol, untyped]

      @payload: Array[untyped]

      attr_reader details: Hash[Symbol, untyped]

      attr_reader reason: String

      attr_reader args: Array[untyped]

      attr_reader kwargs: Hash[Symbol, untyped]

      def initialize: (Hash[Symbol, untyped] details, String reason, *Array[untyped] args, **Hash[Symbol, untyped] kwargs) -> void

      def payload: () -> Array[untyped]

      def self.parse: (Array[untyped] wamp_message) -> Abort
    end
  end
end

