module Wampproto
  module Serializer
    # Add common API for serializer
    class Cbor
      def self.serialize: (untyped message) -> Array[untyped]

      def self.deserialize: (Array[Integer] message) -> untyped
    end
  end
end
