module Wampproto
  module Serializer
    # Add common API for serializer
    class JSON
      def self.encode: (untyped message) -> String

      def self.decode: (String message) -> untyped
    end
  end
end

