module Wampproto
  module Serializer
    # Add common API for serializer
    class JSON
      def self.serialize: (Message::Base message) -> String

      def self.deserialize: (String message) -> Message::Base
    end
  end
end

