module Wampproto
  module Serializer
    # Add common API for serializer
    class Msgpack
      def self.serialize: (Message::Base message) -> Array[untyped]

      def self.deserialize: (Array[untyped] message) -> Message::Base
    end
  end
end

