module Wampproto
  module Message
    # Base Interface for the Message(s)
    class Base
      def self.parse: (Array[untyped] msg) -> Base

      def self.type: () -> Integer

      def marshal: () -> Array[untyped]

      def type: () -> Integer
    end
  end
end
