module Wampproto
  module Message
    # publish message
    class Registered < Base
      @request_id: Integer

      @registration_id: Integer

      attr_reader request_id: Integer

      attr_reader registration_id: Integer

      def initialize: (Integer request_id, Integer registration_id) -> void

      def marshal: () -> ::Array[untyped]

      def self.parse: (Array[untyped] wamp_message) -> Registered
    end
  end
end
