module Wampproto
  module Message
    # abort message
    class Subscribe < Base
      @request_id: Integer

      @options: Hash[Symbol, untyped]

      @topic: String

      attr_reader request_id: Integer

      attr_reader options: Hash[Symbol, untyped]

      attr_reader topic: String

      def initialize: (Integer request_id, Hash[Symbol, untyped] options, String topic) -> void

      def marshal: () -> ::Array[untyped]

      def self.parse: (Array[untyped] wamp_message) -> Subscribe
    end
  end
end
